# Generated by Django 3.1.4 on 2020-12-01 15:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la pelicula', max_length=30)),
                ('duracion', models.IntegerField(help_text='Duracion de la pelicula en minutos')),
                ('descripcion', models.TextField()),
                ('detalle', models.TextField()),
                ('genero', models.CharField(max_length=20)),
                ('clasificacion', models.CharField(max_length=20)),
                ('estado', models.BooleanField(default=False)),
                ('fechaComienzo', models.DateField(auto_now_add=True)),
                ('fechaFin', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la sala', max_length=30)),
                ('estado', models.CharField(max_length=20)),
                ('fila', models.IntegerField()),
                ('asiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Proyeccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicio', models.DateField(auto_now_add=True)),
                ('fechaFin', models.DateField(auto_now_add=True)),
                ('horaProyeccion', models.TimeField(auto_now_add=True)),
                ('estado', models.CharField(max_length=20)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.pelicula')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.sala')),
            ],
        ),
        migrations.CreateModel(
            name='Butaca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('fila', models.IntegerField()),
                ('asiento', models.IntegerField()),
                ('proyeccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservations.proyeccion')),
            ],
        ),
    ]
