# Generated by Django 3.1.4 on 2020-12-03 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20201201_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='butaca',
            name='fecha',
            field=models.DateField(),
        ),
    ]
