# Generated by Django 3.1.4 on 2020-12-09 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_auto_20201203_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyeccion',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sala',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
