# Generated by Django 3.1.4 on 2021-01-21 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0005_auto_20201210_0953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pelicula',
            old_name='fechaFin',
            new_name='fechaFinalizacion',
        ),
    ]
